version: '3.7'

services:
  kafka-connect:
    image: confluentinc/cp-kafka-connect-base:7.6.0
    container_name: kafka-connect
    ports:
      - "8084:8083"
    networks:
      - dockercompose_dataops
    volumes:
      - /home/ubuntu/workspace/Spark_Streaming/debezium/kafka-connect.properties:/etc/kafka/kafka-connect.properties:ro
      - /home/ubuntu/workspace/Spark_Streaming/debezium/config.json:/tmp/config.json:ro

networks:
  dockercompose_dataops:
    external: true
